// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Trackwane.AccessControl.Engine")]
[assembly: AssemblyProduct("Trackwane")]
[assembly: AssemblyCompany("Wylesight")]
[assembly: AssemblyMetadata("module", "access-control")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
