version: "2"

services:

  trackwane_access_control:
    build: ./Modules/AccessControl
    container_name: trackwane_access_control
    depends_on:
      - "etcd"
      - "etcd_viewer"
      - "rabbitmq"
      - "prometheus"
      - "grafana"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/Docker/postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: trackwane
      POSTGRES_PASSWORD: trackwane

  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    command: --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --name etcd --data-dir /data
    volumes:
      - ~/Docker/etcd/data:/data
    ports:
      - "2379:2379"

  etcd_viewer:
    image: nikfoundas/etcd-viewer
    container_name: etcd_viewer
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ~/Docker/prometheus/config/:/etc/prometheus/
    command:  -config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
