// <auto-generated/>
using System.Reflection;

[assembly: AssemblyDescriptionAttribute("")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "LocalBuild";
    }
}
