version: "2"

services:

  elasticsearch:
    image: "elasticsearch:1.7.4"
    network_mode: "host"
    container_name: elasticsearch
    volumes:
      - "/opt/docker/elasticsearch/:/usr/share/elasticsearch/config"
    environment:
      ES_HEAP_SIZE: 1g
    ports:
      - "9300:9300"
      - "9200:9200"

  mongodb:
    image: "mongo:3.0.4"
    network_mode: "host"
    container_name: mongodb
    command: "mongod --config /conf/mongo.conf"
    ports:
      - "27017:27017"
    volumes:
      - "/opt/docker/mongo:/conf/"

  postgres:
    image: postgres
    network_mode: "host"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker/postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: trackwane
      POSTGRES_PASSWORD: trackwane

  rabbitmq:
    container_name: rabbitmq
    network_mode: "host"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
