version: "2"

services:

  postgres:
    image: postgres
    network_mode: "host"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker/postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: trackwane
      POSTGRES_PASSWORD: trackwane

  rabbitmq:
    container_name: rabbitmq
    network_mode: "host"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
