version: "2"

services:

  graylog:
    image: graylog2/allinone
    container_name: graylog
    ports:
      - "8888:80"
      - "12201:12201/udp" # GELF input
    volumes:
      - "/opt/docker/graylog:/data"

  logspout:
    image: "micahhausler/logspout:gelf"
    container_name: logspout
    network_mode: "host"
    command: "gelf://127.0.0.1:12201 --publish=0.0.0.0:9999:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HTTP_PORT: 9843
    ports:
      - "8888:80"

  prometheus:
    image: prom/prometheus
    network_mode: "host"
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/docker/prometheus/config/:/etc/prometheus/
    command:  -config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    network_mode: "host"
    container_name: grafana
    ports:
      - "3000:3000"
