// <auto-generated/>
using System.Reflection;

[assembly: AssemblyDescriptionAttribute("Provides the specification tests for the Trackwane Management module")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "LocalBuild";
    }
}
