// <auto-generated/>
using System.Reflection;

[assembly: AssemblyDescriptionAttribute("sdfsdf")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "LocalBuild";
    }
}
